### ISSUE TITLE
Module installation fails

### ISSUE THREAD

**Issue by teobais** [davidmarkclements/nw-shot#3]
Hello,

seems hat there's an installation issue when running `npm install nw-shot` : 

![image](https://cloud.githubusercontent.com/assets/5684688/10863585/9e15aba0-7fda-11e5-8b89-02d4ca691fcd.png)

I'm on Windows 7 x64 and the `npm-debug.log` file is sent to your personal mail account.

**Comment by mikemaccana** [comment]
Getting the same thing here, using OS X, on the current stable node `4.2.1`:

```
> nw-shot@4.2.0 postinstall /Users/mike/Documents/Conference Talks/burn-everything-down/node_modules/nw-shot
> install-nw

/Users/mike/Documents/Conference Talks/burn-everything-down/node_modules/install-nw/cmd.js:121
  version = [v.major, v.minor, v.patch].join('.');
              ^

TypeError: Cannot read property 'major' of null
    at down (/Users/mike/Documents/Conference Talks/burn-everything-down/node_modules/install-nw/cmd.js:121:15)
    at init (/Users/mike/Documents/Conference Talks/burn-everything-down/node_modules/install-nw/cmd.js:72:11)
    at Object.<anonymous> (/Users/mike/Documents/Conference Talks/burn-everything-down/node_modules/install-nw/cmd.js:41:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by davidmarkclements** [comment]
Hmm they may have changed the url scheme again - will look into

**Comment by Empereol** [comment]
Is there any progress on this? I'm also getting the same error.

**Comment by the-simian** [comment]
Came here to report this very issue
![nw](https://cloud.githubusercontent.com/assets/954596/12684545/18bcf69c-c685-11e5-867e-c730c0979b71.png)

```
npm version 3.3.12
node version 5.5.0

```

**Comment by davidmarkclements** [comment]
hey @the-simian - what OS & what node version - I just tried to reproduce on OS X with node v5.5.0 and I'm not able to reproduce the problem

**Comment by the-simian** [comment]
The OS is windows 10. But i also confirmed it on Windows 7.

Hey, interestingly I'm generally experiencing postinstall script issues with packages like this, and others since npm changed to the [nondeterministic way of doing it](https://docs.npmjs.com/how-npm-works/npm3-nondet). Here is a similar situation on another similar module: https://github.com/FWeinb/node-webkit-screenshot/issues/14

 I was able to get a fix on that module by (in the postinstall script) cd'ing into one directory down first. I'm still actively looking into all this, so maybe I'll more later.

**Comment by davidmarkclements** [comment]
ah right right - good call - I switched back to npm2 for speed reasons

this issue is probably to do with the flat structure vs tree structure

**Comment by the-simian** [comment]
Yeah I am considering it as well, though I was able to get improved speeds by `npm set progress=false`

**Comment by davidmarkclements** [comment]
yah I head about that - haven't tried it yet

On Fri, Jan 29, 2016 at 8:35 PM, Jesse Harlin notifications@github.com
wrote:

> Yeah I am considering it as well, though I was able to get improved speeds
> by `npm set progress=false'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/davidmarkclements/nw-shot/issues/3#issuecomment-176956948
> .

## 

David Mark Clements Ltd is a company registered in Northern Ireland.
Registered number: NI617728. Registered office: Unit 22a, Pennybridge
Industrial Estate,
Ballymena, Antrim, BT42 3HB

**Comment by duereg** [comment]
Having the same issue on OSX, with node 4.2.4, npm 3.5.3

**Comment by the-simian** [comment]
hey I wanted to pop in and add, that I didn't end up getting this one to work, but we were able to solve postInstall script errors in a similar project by adding a cd to the right directory first.

see here: https://github.com/FWeinb/node-webkit-screenshot/pull/15

I didn't dig long enough into this module to see if the fix is the same, but that might be useful.

**Comment by KJTsanaktsidis** [comment]
I was able to make this install by adding `"nw" : "0.12.3"` to the root of our package.json file
